version: '3'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=phoneCatalog
      - MYSQL_ROOT_PASSWORD=phonePassword1
      - MYSQL_PASSWORD=phonePassword1

  web:
    image: jorgeap/phonecatalog:latest
    ports:
      - 8080:8080
    restart: always
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/phoneCatalog
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=phonePassword1

